name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=2.2.1
  - pytest=8.2.2
  - scipy=1.12.0
  - pip=23.3.1
  - pip:
    - mlflow==2.8.1
    - wandb==0.16.0